twig:
    default_path: '%kernel.project_dir%/templates'

    form_themes: ['bootstrap_4_layout.html.twig']

    globals:

            totalprice: 0
            totalpayment: 0
            studentresult: 0
            searchcourse: 0
            amounttotal: 0